# -*- coding: utf-8 -*-
"""P-105.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SkNKr8I4ZLxbczMSLfLYHx4IiMw7Qvz5
"""

from google.colab import files
data_to_load=files.upload()
import csv
import math
with open("data.csv",newline="") as f:
  reader=csv.reader(f)
  file_data=list(reader)
  data=file_data[0]
  def mean(data):
    n=len(data)
    total=0
    for x in data:
      total+=int(x)
    mean=total/n
    return mean
  squared_list=[]
  for number in data:
    a=int(number)-mean(data)
    a=a**2
    squared_list.append(a)
  sum=0
  for i in squared_list:
    sum=sum+i
    result=sum/(len(data)-1)
  std=math.sqrt(result)
  print(std)